export const doctors = [
  {
    id: 1,
    name: "Dr. Ana Petrović",
    specialty: "Kardiolog",
    experience: "12 god.",
    rating: "4.9",
    reviews: 142,
    initials: "AP",
    available: true,
    nextSlot: "Danas, 14:00",
    tags: ["EKG", "Holter", "Ehokardiografija"],
    gradient: "from-blue-500 to-blue-700",
    bio: "Specijalista kardiovaskularne medicine. Fokus na preventivnoj kardiologiji i ranoj dijagnostici bolesti srca.",
  },
  {
    id: 2,
    name: "Dr. Marko Nikolić",
    specialty: "Neurolog",
    experience: "9 god.",
    rating: "4.8",
    reviews: 98,
    initials: "MN",
    available: true,
    nextSlot: "Danas, 16:30",
    tags: ["Migrena", "EEG", "Epilepsija"],
    gradient: "from-cyan-500 to-cyan-700",
    bio: "Neurolog sa posebnim interesom za headache medicinu i neurološke poremećaje spavanja.",
  },
  {
    id: 3,
    name: "Dr. Jelena Jović",
    specialty: "Dermatolog",
    experience: "7 god.",
    rating: "4.9",
    reviews: 215,
    initials: "JJ",
    available: false,
    nextSlot: "Sutra, 09:00",
    tags: ["Akne", "Dermatoskopija", "Ekcem"],
    gradient: "from-teal-500 to-teal-700",
    bio: "Dermatolog sa specijalizacijom u kozmetičkoj dermatologiji i lečenju hroničnih kožnih bolesti.",
  },
  {
    id: 4,
    name: "Dr. Stefan Vuković",
    specialty: "Ortoped",
    experience: "11 god.",
    rating: "4.7",
    reviews: 173,
    initials: "SV",
    available: true,
    nextSlot: "Danas, 17:00",
    tags: ["Kičma", "Sport", "Koleno"],
    gradient: "from-indigo-500 to-indigo-700",
    bio: "Ortopedski hirurg specijalizovan za sportske povrede i degenerativne bolesti zglobova.",
  },
  {
    id: 5,
    name: "Dr. Milica Đorđević",
    specialty: "Internista",
    experience: "14 god.",
    rating: "4.8",
    reviews: 301,
    initials: "MĐ",
    available: true,
    nextSlot: "Danas, 11:00",
    tags: ["Dijabetes", "Hipertenzija", "Preventiva"],
    gradient: "from-rose-500 to-rose-700",
    bio: "Internista sa fokusom na preventivnu medicinu, dijabetes i metaboličke poremećaje.",
  },
  {
    id: 6,
    name: "Dr. Ivan Lazić",
    specialty: "Psihijatar",
    experience: "8 god.",
    rating: "4.9",
    reviews: 187,
    initials: "IL",
    available: false,
    nextSlot: "Sutra, 11:00",
    tags: ["Anksioznost", "Depresija", "Terapija"],
    gradient: "from-purple-500 to-purple-700",
    bio: "Psihijatar sa integrativnim pristupom lečenju mentalnog zdravlja i stres menadžmentu.",
  },
  {
    id: 7,
    name: "Dr. Nataša Simić",
    specialty: "Oftalmolog",
    experience: "10 god.",
    rating: "4.7",
    reviews: 134,
    initials: "NS",
    available: true,
    nextSlot: "Danas, 15:30",
    tags: ["Katarakt", "Glaukom", "Dioptrija"],
    gradient: "from-amber-500 to-amber-700",
    bio: "Specijalista bolesti oka sa dugogodišnjim iskustvom u dijagnostici i hirurgiji oka.",
  },
  {
    id: 8,
    name: "Dr. Dragan Popović",
    specialty: "Ginekolog",
    experience: "16 god.",
    rating: "4.8",
    reviews: 412,
    initials: "DP",
    available: true,
    nextSlot: "Danas, 13:00",
    tags: ["Ultrazvuk", "Prevencija", "Trudnoća"],
    gradient: "from-pink-500 to-pink-700",
    bio: "Ginekolog sa posebnim iskustvom u praćenju trudnoće i preventivnoj ginekologiji.",
  },
  {
    id: 9,
    name: "Dr. Aleksandra Ristić",
    specialty: "Internista",
    experience: "6 god.",
    rating: "4.6",
    reviews: 77,
    initials: "AR",
    available: false,
    nextSlot: "Sreda, 10:00",
    tags: ["Štitna žlezda", "Anemija", "Reuma"],
    gradient: "from-emerald-500 to-emerald-700",
    bio: "Mladi internista specijalizovana za endokrinologiju i bolesti štitne žlezde.",
  },
  {
    id: 10,
    name: "Dr. Petar Stojanović",
    specialty: "Kardiolog",
    experience: "18 god.",
    rating: "4.9",
    reviews: 389,
    initials: "PS",
    available: true,
    nextSlot: "Danas, 10:00",
    tags: ["Aritmija", "Kateterizacija", "EKG"],
    gradient: "from-blue-600 to-blue-800",
    bio: "Senior kardiolog sa ogromnim iskustvom u intervencijskoj kardiologiji i lečenju aritmija.",
  },
  {
    id: 11,
    name: "Dr. Marina Ilić",
    specialty: "Neurolog",
    experience: "11 god.",
    rating: "4.8",
    reviews: 156,
    initials: "MI",
    available: true,
    nextSlot: "Danas, 12:30",
    tags: ["Multipla skleroza", "Tremor", "EMG"],
    gradient: "from-cyan-600 to-cyan-800",
    bio: "Neurolog sa fokusom na demijelinizacione bolesti i poremećaje pokreta.",
  },
  {
    id: 12,
    name: "Dr. Bojan Đukić",
    specialty: "Ortoped",
    experience: "9 god.",
    rating: "4.7",
    reviews: 121,
    initials: "BĐ",
    available: false,
    nextSlot: "Sutra, 08:30",
    tags: ["Rame", "Zglob kuka", "Artroskopija"],
    gradient: "from-indigo-600 to-indigo-800",
    bio: "Ortoped specijalizovan za artroskopsku hirurgiju ramena i kuka.",
  },
  {
    id: 13,
    name: "Dr. Jovana Filipović",
    specialty: "Dermatolog",
    experience: "5 god.",
    rating: "4.7",
    reviews: 88,
    initials: "JF",
    available: true,
    nextSlot: "Danas, 16:00",
    tags: ["Psorijaza", "Alergija", "Lazer"],
    gradient: "from-teal-600 to-teal-800",
    bio: "Dermatolog sa posebnim interesovanjem za alergološku dermatologiju i lazer tretmane.",
  },
  {
    id: 14,
    name: "Dr. Nikola Stanković",
    specialty: "Urolog",
    experience: "13 god.",
    rating: "4.8",
    reviews: 204,
    initials: "NŠ",
    available: true,
    nextSlot: "Danas, 09:30",
    tags: ["Bubreg", "Prostata", "Laparoskopija"],
    gradient: "from-slate-500 to-slate-700",
    bio: "Urolog sa bogatim iskustvom u minimalno invazivnoj hirurgiji bubrega i prostate.",
  },
  {
    id: 15,
    name: "Dr. Tamara Pešić",
    specialty: "Endokrinolog",
    experience: "10 god.",
    rating: "4.9",
    reviews: 178,
    initials: "TP",
    available: false,
    nextSlot: "Sutra, 14:00",
    tags: ["Dijabetes", "Tireoid", "Hormoni"],
    gradient: "from-orange-500 to-orange-700",
    bio: "Endokrinolog posvećena lečenju hormonskih poremećaja, dijabetesa i bolesti štitne žlezde.",
  },
  {
    id: 16,
    name: "Dr. Vladimir Savić",
    specialty: "Pulmolog",
    experience: "15 god.",
    rating: "4.8",
    reviews: 231,
    initials: "VS",
    available: true,
    nextSlot: "Danas, 11:30",
    tags: ["Astma", "HOBP", "Spirometrija"],
    gradient: "from-sky-500 to-sky-700",
    bio: "Pulmolog sa iskustvom u dijagnostici i lečenju hroničnih bolesti pluća i disajnih puteva.",
  },
  {
    id: 17,
    name: "Dr. Katarina Mitrović",
    specialty: "Reumatolog",
    experience: "8 god.",
    rating: "4.7",
    reviews: 112,
    initials: "KM",
    available: true,
    nextSlot: "Danas, 15:00",
    tags: ["Artritis", "Lupus", "Osteoporoza"],
    gradient: "from-violet-500 to-violet-700",
    bio: "Reumatolog specijalizovana za autoimune bolesti zglobova i vezivnog tkiva.",
  },
  {
    id: 18,
    name: "Dr. Zoran Bogdanović",
    specialty: "Gastroenterolog",
    experience: "17 god.",
    rating: "4.9",
    reviews: 267,
    initials: "ZB",
    available: false,
    nextSlot: "Sreda, 09:00",
    tags: ["Endoskopija", "IBD", "Jetra"],
    gradient: "from-lime-600 to-lime-800",
    bio: "Gastroenterolog sa dugogodišnjim iskustvom u endoskopiji i lečenju hroničnih bolesti creva.",
  },
  {
    id: 19,
    name: "Dr. Maja Tomić",
    specialty: "Pedijatar",
    experience: "12 god.",
    rating: "4.9",
    reviews: 445,
    initials: "MT",
    available: true,
    nextSlot: "Danas, 08:30",
    tags: ["Novorođenče", "Vakcinacija", "Razvoj"],
    gradient: "from-pink-400 to-pink-600",
    bio: "Pedijatar sa bogatim iskustvom u praćenju rasta i razvoja dece od rođenja do adolescencije.",
  },
  {
    id: 20,
    name: "Dr. Aleksandar Kovač",
    specialty: "Hirurg",
    experience: "20 god.",
    rating: "4.9",
    reviews: 532,
    initials: "AK",
    available: true,
    nextSlot: "Danas, 13:30",
    tags: ["Abdomen", "Laparoskopija", "Hernia"],
    gradient: "from-red-600 to-red-800",
    bio: "Senior hirurg sa dvadesetogodišnjim iskustvom u abdominalnoj i laparoskopskoj hirurgiji.",
  },
  {
    id: 21,
    name: "Dr. Snežana Đorđević",
    specialty: "Ginekolog",
    experience: "14 god.",
    rating: "4.8",
    reviews: 323,
    initials: "SĐ",
    available: false,
    nextSlot: "Sutra, 10:30",
    tags: ["Kolposkopija", "Menopauza", "HPV"],
    gradient: "from-fuchsia-500 to-fuchsia-700",
    bio: "Ginekolog specijalizovana za kolposkopiju, HPV prevenciju i lečenje menopauze.",
  },
  {
    id: 22,
    name: "Dr. Rastko Milić",
    specialty: "Psihijatar",
    experience: "7 god.",
    rating: "4.8",
    reviews: 143,
    initials: "RM",
    available: true,
    nextSlot: "Danas, 17:30",
    tags: ["PTSD", "Bipolarni", "CBT"],
    gradient: "from-purple-600 to-purple-800",
    bio: "Psihijatar specijalizovan za traumatske poremećaje i kognitivno-bihejvioralnu terapiju.",
  },
  {
    id: 23,
    name: "Dr. Dragana Živković",
    specialty: "Endokrinolog",
    experience: "9 god.",
    rating: "4.7",
    reviews: 119,
    initials: "DŽ",
    available: true,
    nextSlot: "Danas, 10:30",
    tags: ["Gojaznost", "Insulinska rezistencija", "Nadbubreg"],
    gradient: "from-orange-600 to-orange-800",
    bio: "Endokrinolog sa posebnim interesom za metabolički sindrom, gojaznost i insulinsku rezistenciju.",
  },
  {
    id: 24,
    name: "Dr. Miloš Radovanović",
    specialty: "Gastroenterolog",
    experience: "11 god.",
    rating: "4.8",
    reviews: 188,
    initials: "MR",
    available: false,
    nextSlot: "Četvrtak, 11:00",
    tags: ["Kolonoskopija", "Refluks", "Pankreatitis"],
    gradient: "from-green-600 to-green-800",
    bio: "Gastroenterolog sa iskustvom u dijagnostičkim procedurama i lečenju bolesti digestivnog sistema.",
  },
  {
    id: 25,
    name: "Dr. Vesna Ilić",
    specialty: "Pedijatar",
    experience: "16 god.",
    rating: "4.9",
    reviews: 501,
    initials: "VI",
    available: true,
    nextSlot: "Danas, 09:00",
    tags: ["Alergije kod dece", "Astma", "Imunizacija"],
    gradient: "from-rose-400 to-rose-600",
    bio: "Pedijatar sa specijalizacijom u alergologiji i imunologiji kod dece.",
  },
  {
    id: 26,
    name: "Dr. Predrag Marković",
    specialty: "Pulmolog",
    experience: "13 god.",
    rating: "4.7",
    reviews: 167,
    initials: "PM",
    available: true,
    nextSlot: "Danas, 14:30",
    tags: ["Apnea", "Bronhiektazija", "CT pluća"],
    gradient: "from-sky-600 to-sky-800",
    bio: "Pulmolog fokusiran na poremećaje spavanja, apneju i strukturalne bolesti pluća.",
  },
  {
    id: 27,
    name: "Dr. Tijana Vasić",
    specialty: "Reumatolog",
    experience: "6 god.",
    rating: "4.6",
    reviews: 84,
    initials: "TV",
    available: false,
    nextSlot: "Petak, 09:30",
    tags: ["Fibromialgija", "Giht", "Infiltracije"],
    gradient: "from-violet-600 to-violet-800",
    bio: "Reumatolog specijalizovana za fibromialgiju, giht i terapijske infiltracije zglobova.",
  },
];

export const featuredDoctors = doctors.slice(0, 4);
